easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Avis
        - App\Entity\Ingredients
        - App\Entity\Recipe
        - App\Entity\Steps
        - App\Entity\Tag
        - App\Entity\Unite
        - App\Entity\Utensil
